# Generated by Django 2.1 on 2018-09-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0003_buyer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='street_address1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='street_address2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
