# Generated by Django 2.0 on 2018-09-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0006_auto_20180910_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
