# Generated by Django 2.0 on 2018-09-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0007_auto_20180910_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
